import "~/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="uk">
      <body className={`font-sans ${inter.variable}`}>
        <main className="flex min-h-[100dvh] flex-col items-center justify-start overflow-y-auto bg-[#4169E1] px-2 text-white">
          {children}
        </main>
      </body>
    </html>
  );
}
